# The folder to output
outputFolder: "out"

# The handling method for colors
colorMode: cmi
# vanilla: &#RRGGBB
# vanilla2: &x&R&R&G&G&B&B
# cmi: {#RRGGBB}
# minimessage: <#RRGGBB>
# minedown: &#RRGGBB&

# The handling method for item groups
groupMode: none
# Example:    item_group: example
# prefix:     item_group: rsc_example
# namespace:  item_group: rykenslimecustomizer:example
# none:       item_group: example

# Change the version of all the saveditems
setAllSaveditems_v: none
# none: Not to change
# Number: Change the version to the number
# Example: setAllSaveditems_v: 2975

# Auto create versioned object (Unsafe)
enableCreateVersionedObject: false

menus:
  sections:
    ##########################################################
    # -------------------Preset Parameters-------------------
    # Don't change the following parameters
    B: gray_stained_glass_pane # Default background
    I: blue_stained_glass_pane # Default input background
    O: orange_stained_glass_pane  # Default output background
    N: continue  # Continue the slot
    P: progress  # The progress bar slot
    i: input  # The empty slot for input
    o: output # The empty slot for output
    # -------------------Preset Parameters-------------------
    ##########################################################

    # Define other sections here
    # See https://rsc.hiworldmc.com/#/format/universal-item-format
    # a:
    #   name: '&a'
    #   material_type: mc
    #   material: BEDROCK
    #   modelId: 123456789
    #   glow: false
    #   lore:
    #     - The first line
    #     - The second line
    # b: this_is_a_mc_item
    # c:
    #   material_type: skull_hash
    #   material: this_is_skull_hash
    n:  # Placeholder
      material_type: none

  # Machines' menu
  machines:
    title: "%name%"  # %name% will be replaced by the machine's name
    background-slots: # Except for 'i' and 'o', all slots will be read
      - "BBBBBBBBB"
      - "IIIIBOOOO"
      - "IiiIPOooO"
      - "IIIIBOOOO"
      - "BBBBBBBBB"
    input-slots: # Only i will be read
      - "BBBBBBBBB"
      - "IIIIBOOOO"
      - "IiiIPOooO"
      - "IIIIBOOOO"
      - "BBBBBBBBB"
    output-slots: # Only o will be read
      - "BBBBBBBBB"
      - "IIIIBOOOO"
      - "IiiIPOooO"
      - "IIIIBOOOO"
      - "BBBBBBBBB"
  # Generators' menu
  generators:
    title: "%name%"  # %name% will be replaced by the generator's name
    background-slots: # Except for 'i' and 'o', all slots will be read
      - "BBBBBBBBB"
      - "IIIIBOOOO"
      - "IiiIPOooO"
      - "IIIIBOOOO"
      - "BBBBBBBBB"
    input-slots: # Only i will be read
      - "BBBBBBBBB"
      - "IIIIBOOOO"
      - "IiiIPOooO"
      - "IIIIBOOOO"
      - "BBBBBBBBB"
    output-slots: # Only o will be read
      - "BBBBBBBBB"
      - "IIIIBOOOO"
      - "IiiIPOooO"
      - "IIIIBOOOO"
      - "BBBBBBBBB"
  # Material generators' menu
  material-generators:
    title: "%name%"  # %name% will be replaced by the material generator's name
    background-slots: # Except for 'i' and 'o', all slots will be read
      - "Poooooooo"
    output-slots: # Only o will be read
      - "Poooooooo"

lores:
  # Full copy SlimeCustomizer lores
  full-copy-slimecustomizer: true
additions: # Addition config
  categories: {} # Categories
  #categories:
    #group1: # Group1
    #  items: # Which item to select to add config
    #  - '__example_item'
    #  - '__all__' # All the items
    #  config: # Content of the config
    #    register:
    #      conditions:
    #      - "version >= 1.16"
    #groups2: {} # Group2, Name it by yourself
  mob_drops: {} # Mob drops, similar to categories
  geo_resources: {}
  items: {}
  capacitors: {}
  machines: {}
  generators:
    group1:
      items:
      - '__all__'
      config:
        lateInit: true
  solar_generators:
    group1:
      items:
      - '__all__'
      config:
        lateInit: true
  material_generators:
    group1:
      items:
      - '__all__'
      config:
        lateInit: true
  researches: {}

info:
  # Enable or disable the addon (When false, it will read sc-addon.yml)
  enable: false
  # The id of the addon in RykenSlimeCustomizer
  id: RSC_SlimefunExpansion
  # The name of the addon
  name: Unknown addon
  # The addon depends which based on RykenSlimeCustomizer
  depends: []
  # The plugin depends which based on Slimefun (Usually won't auto load)
  pluginDepends:
  - Slimefun
  #- GuizhanLibPlugin
  # The version of the addon
  version: 1.0 SNAPSHOT
  # The description of the addon
  description: No description
  # The authors of the addon
  authors:
  - ''
  # The github repository of the addon
  repo: ''

# Don't change this
config-version: 1.6-SNAPSHOT
