# 不要删除已有的参数的名字！

# 转换后输出到哪个文件夹
outputFolder: "translated"

colorMode: cmi
# vanilla: &#RRGGBB
# vanilla2: &x&R&R&G&G&B&B
# cmi: {#RRGGBB}
# minimessage: <#RRGGBB>
# minedown: &#RRGGBB&

# 物品组处理方式
groupMode: none
# 示例:       item_group: example
# prefix:     item_group: rsc_example
# namespace:  item_group: rykenslimecustomizer:example
# none:       item_group: example

# 设置所有保存物品的版本号
setAllSaveditems_v: none
# none: 不做修改
# 数字: 改为对应数字
# 示例: setAllSaveditems_v: 2975

menus:
  sections:
    #########################################
    # -------------预设参数-------------
    # 已有参数的名字不可修改！
    B: gray_stained_glass_pane # 背景
    I: blue_stained_glass_pane # 输入槽背景
    O: orange_stained_glass_pane  # 输出槽背景
    N: continue  # 跳过当前槽
    P: progress  # 进度条
    i: input  # 输入槽位
    o: output # 输出槽位
    # -------------预设参数-------------
    #########################################

    # 可自定义其他的，不要与上面的重复
    # 详见 rsc-wiki.通用物品格式
    # a:
    #   name: '&a'
    #   material_type: mc
    #   material: BEDROCK
    #   modelId: 114514
    #   glow: false
    #   lore:
    #     - 第1行
    #     - 第114514行
    #   progressbar: true
    #   progressBarItem:
    #     name: '&a'
    #     material_type: mc
    #     material: OAK_PLANKS
    # b: this_is_a_mc_item
    # c:
    #   material_type: skull_hash
    #   material: this_is_skull_hash

  # 机器菜单
  machines:
    title: "%name%"  # %name% 自动转为机器名称
    slots:
      - "BBBBBBBBB"
      - "IIIIBOOOO"
      - "IiiIPOooO"
      - "IIIIBOOOO"
      - "BBBBBBBBB"
  # 发电机菜单
  generators:
    title: "%name%"  # %name% 自动转为发电机名称
    slots:
      - "BBBBBBBBB"
      - "IIIIBOOOO"
      - "IiiIPOooO"
      - "IIIIBOOOO"
      - "BBBBBBBBB"
  # 材料生成器菜单
  material-generators:
    title: "%name%"  # %name% 自动转为材料生成器名称
    slots:
      - "POooooooO"
lores:
  # 是否完全复制 SlimeCutomizer 的格式
  full-copy-slimecustomizer: true
additions: # 附加参数
  categories: {} # 分类
  #categories:
    #group1: # 分组1
    #  items: # 适用物品，不存在会跳过
    #  - '__example_item'
    #  - '__all__' # 全部内容，不建议使用 
    #  config: # 配置内容
    #    register:
    #      conditions:
    #      - "version >= 1.16"
    #groups2: {} # 分组2，自定名字
  mob_drops: {} # 生物掉落。同上格式
  geo_resources: {}
  items: {}
  capacitors: {}
  machines: {}
  generators:
    group1:
      items:
      - '__all__'
      config:
        lateInit: true
  solar_generators:
    group1:
      items:
      - '__all__'
      config:
        lateInit: true
  material_generators:
    group1:
      items:
      - '__all__'
      config:
        lateInit: true
  researches: {}

info:
  # 是否使用此设置（false时自动读取sc-addon.yml）
  enable: false
  # 附属在RSC内的附属id
  id: RSC_SlimefunExpansion
  # 附属名字
  name: Unknown addon
  # 后置插件
  depends: []
  # 硬前置插件（通常不会自动加载）
  pluginDepends:
  - Slimefun
  #- GuizhanLibPlugin
  # 附属版本
  version: 1.0-SNAPSHOT
  # 附属介绍
  description: No description
  # 附属作者
  authors:
  - ''
  # 附属仓库
  repo: ''
